image: node:10.15.3

pipelines:  
  default:
    - step:
        script:
          - echo "Touch base"
  branches: 
    release/staging:
      - step: 
          name: Publish to docker registry
          deployment: Publish to Docker Registry
          services:
            - docker
          caches:
            - docker
          script:
            - docker login -u $dockerUserName -p $dockerPassword
            - docker build -t martinchinaka/npf-admin .
            - docker push martinchinaka/npf-admin 
    release/production:
      - step: 
          name: Publish to docker registry
          deployment: Publish to Docker Registry
          services:
            - docker
          caches:
            - docker
          script:
            - docker login -u $dockerUserName -p $dockerPassword
            - docker build -t martinchinaka/npf-admin:prod .
            - docker push martinchinaka/npf-admin:prod
definitions:
  services:
    docker:
      memory: 3072